projectName = "FreightFrenzy"
configPath = "TeamCode/src/main/java/org/firstinspires/ftc/teamcode/util/OpModeBase.kt"

move = [
    { old = "TeamCode/build/outputs/apk/$(target)/TeamCode-$(target).apk", new = "TeamCode-$(target)-$(config).apk" },
]

[configRegex]
find = "RobotConfig.activate(hardwareMap, .*)"
replace = "RobotConfig.activate(hardwareMap, $(config))"

[configurations]
programmingBoard = "::programmingBoard"
fullRobot = "::fullRobot"

[targets]
debug = ["./gradlew", "assembleDebug"]
release = ["./gradlew", "assembleRelease"]
