projectName = "FreightFrenzy"
configPath = "TeamCode/src/main/java/org/manchestermachinemakers/RobotConfig.java"

move = [
    { old = "TeamCode/build/outputs/apk/$(target)/TeamCode-$(target).apk", new = "TeamCode-$(target)-$(config).apk" },
]

[configRegex]
find = "DriveBase.use(.*);"
replace = "DriveBase.use(new $(config)());"

[configurations]
fullRobot = "FullRobot"
programmingBoard = "ProgrammingBoard"

[targets]
debug = ["./gradlew", "assembleDebug"]
release = ["./gradlew", "assembleRelease"]
