configPath = "TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt"

move = [
    { from = "TeamCode/build/outputs/apk/$(target)/TeamCode-$(target).apk", to = "TeamCode-$(target)-$(config).apk" },
]

[configRegex]
find = "fun init() { .* }"
replace = "fun init() { $(config) }"

[configurations]
programmingBoard = "programmingBoard()"
fullRobot = "fullRobot()"

[targets]
debug = ["./gradlew", "assembleDebug"]
release = ["./gradlew", "assembleRelease"]
