configPath = "dummy.txt"

move = [
    { from = "TeamCode/build/outputs/apk/$(target)/TeamCode-$(target).apk", to = "TeamCode-$(target)-$(config).apk" },
]

[configRegex]
find = ""
replace = ""

[configurations]
default = ""

[targets]
debug = ["./gradlew", "assembleDebug"]
release = ["./gradlew", "assembleRelease"]
